"""Deterministic, read-only release validation for every active mission.

This module exercises the currently enabled victory-hook generation path fully
in memory.  It deliberately does not claim that gameplay randomization is
release-ready while the Reloaded reward and production catalogues are gated.
"""

import hashlib
import json
from collections import Counter

from randomizer.config.game_profile import (
    GAMEPLAY_CATALOGUES_READY,
    GENERATED_HOOK_PREFIX,
)
from randomizer.config.static import static_config_section
from randomizer.content.inventory import read_rules_sections
from randomizer.maps.generated import file_sha256
from randomizer.maps.hooks import MAX_MAP_ACTION_LINE_LENGTH
from randomizer.maps.identity_safety import (
    capture_authored_identity_contract,
    validate_authored_identity_contract,
)
from randomizer.maps.ini import (
    IniLines,
    parse_action_groups,
    read_text,
    section_lines,
    section_value_map_preserve,
)
from randomizer.maps.progress_hooks import (
    inject_check_markers,
    pending_check_hook_plan,
)
from randomizer.missions.installation import resolve_installed_scenario
from randomizer.missions.metadata import MISSION_METADATA
from randomizer.missions.overrides import (
    MISSION_OBJECTIVE_HOOK_ACTION_IDS,
    MISSION_OBJECTIVE_HOOK_ACTION_REDIRECTS,
    MISSION_VICTORY_HOOK_ACTION_IDS,
)


GENERATED_MAP_MARKER = (
    '; Generated by C&C Reloaded Randomizer Launcher objective hook'
)
PACKED_SECTIONS = {
    'previewpack', 'isomappack5', 'overlaypack', 'overlaydatapack',
}
HOOK_REGISTRIES = {
    'teamtypes': 'RLRVT',
    'taskforces': 'RLRVF',
    'scripttypes': 'RLRVS',
}
HOOK_SECTION_PREFIXES = tuple(HOOK_REGISTRIES.values())
MAX_GENERATED_ID_LENGTH = int(static_config_section(
    'map_rules.json', 'engine_limits', dict
)['max_ares_type_id_length'])


def render_generated_hook_map(lines):
    """Render an in-memory hook map using the owned-file marker."""
    return (
        GENERATED_MAP_MARKER + '\r\n'
        + '\r\n'.join(lines)
        + '\r\n'
    ).encode('utf-8')


def generate_victory_hook_map(
    metadata,
    installed_sections,
    capture_identity=True,
):
    """Generate one reviewed victory-hook map without writing game files."""
    source_path = resolve_installed_scenario(metadata['scenario'])
    source_hash_before = file_sha256(source_path)
    if source_hash_before != metadata['source_sha256']:
        raise ValueError(
            f'source hash differs from reviewed metadata: '
            f'{source_hash_before} != {metadata["source_sha256"]}'
        )

    original = IniLines(read_text(source_path).splitlines())
    contract = (
        capture_authored_identity_contract(original, installed_sections)
        if capture_identity else None
    )
    generated = IniLines(original)
    checks = [{'id': 'victory', 'name': 'Victory', 'unlocked': False}]
    configured_ids = tuple(
        MISSION_VICTORY_HOOK_ACTION_IDS.get(metadata['code'], ())
    )
    plan, missing_victory, _completed = pending_check_hook_plan(
        generated,
        checks,
        configured_ids,
        MISSION_OBJECTIVE_HOOK_ACTION_IDS.get(metadata['code'], {}),
        MISSION_OBJECTIVE_HOOK_ACTION_REDIRECTS.get(metadata['code'], {}),
    )
    if missing_victory:
        raise ValueError('reviewed victory hook is missing')
    expected_action_ids = tuple(
        action_id.lower()
        for action_id in metadata['verified_victory_action_ids']
    )
    planned_action_ids = tuple(
        action_id.lower() for _check, action_id in plan
    )
    if planned_action_ids != expected_action_ids:
        raise ValueError(
            'planned victory Actions differ from reviewed metadata: '
            f'{planned_action_ids} != {expected_action_ids}'
        )

    markers, failures = inject_check_markers(
        generated,
        metadata['code'],
        plan,
        metadata['player_house'],
    )
    if failures:
        raise ValueError(
            'marker injection failed for Actions: '
            + ', '.join(action_id for _check, action_id in failures)
        )
    if not markers or set(markers.values()) != {'victory'}:
        raise ValueError('generated marker set is incomplete')
    if file_sha256(source_path) != source_hash_before:
        raise ValueError('source map hash changed during in-memory generation')
    return original, generated, contract, markers, configured_ids, len(plan)


def _new_registry_ids(original, generated, section, prefix):
    before = section_value_map_preserve(original, section)
    after = section_value_map_preserve(generated, section)
    before_keys = {key.lower() for key in before}
    added = {
        key: value for key, value in after.items()
        if key.lower() not in before_keys
    }
    bad_values = [value for value in added.values() if not value.startswith(prefix)]
    if bad_values:
        raise ValueError(
            f'[{section}] contains non-hook additions: {bad_values[:4]}'
        )
    for key, value in before.items():
        current = next(
            (item for name, item in after.items() if name.lower() == key.lower()),
            None,
        )
        if current != value:
            raise ValueError(f'[{section}] changed authored entry {key}')
    return tuple(added.values())


def _strip_approved_mutations(original, generated, action_ids, generated_ids):
    """Reverse only approved hook edits; remainder must equal source lines."""
    original_actions = section_value_map_preserve(original, 'Actions')
    original_action_lines = {
        key.lower(): f'{key}={value}' for key, value in original_actions.items()
    }
    allowed_actions = {str(action_id).lower() for action_id in action_ids}
    generated_ids_lower = {item.lower() for item in generated_ids}
    output = []
    section = ''
    skip_section = False
    for line in generated:
        stripped = line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            section = stripped[1:-1].strip()
            skip_section = section.lower() in generated_ids_lower
            if skip_section:
                continue
        if skip_section:
            continue
        if '=' in line:
            key, value = line.split('=', 1)
            section_lower = section.lower()
            if (
                section_lower in HOOK_REGISTRIES
                and value.strip().lower() in generated_ids_lower
            ):
                continue
            if section_lower == 'actions' and key.strip().lower() in allowed_actions:
                output.append(original_action_lines[key.strip().lower()])
                continue
        output.append(line)

    while output and not output[-1].strip():
        output.pop()
    expected = list(original)
    while expected and not expected[-1].strip():
        expected.pop()
    if output != expected:
        mismatch = next(
            (
                index for index, (actual, wanted) in enumerate(
                    zip(output, expected), start=1
                ) if actual != wanted
            ),
            min(len(output), len(expected)) + 1,
        )
        raise ValueError(
            'generated mutation escaped approved hook scope '
            f'near source line {mismatch}'
        )


def _validate_parse(lines, generated_action_ids, generated_section_ids):
    section = ''
    malformed_headers = []
    malformed_actions = []
    for number, line in enumerate(lines, start=1):
        stripped = line.strip()
        header = stripped.split(';', 1)[0].strip()
        if header.startswith('['):
            if not header.endswith(']'):
                if section in PACKED_SECTIONS:
                    continue
                malformed_headers.append(number)
                continue
            section = header[1:-1].strip().lower()
        elif section == 'actions' and '=' in line:
            key, value = line.split('=', 1)
            if (
                key.strip().lower() not in generated_action_ids
                and key.strip().lower() not in generated_section_ids
            ):
                continue
            declared, groups = parse_action_groups(value)
            if not key.strip() or declared != len(groups):
                malformed_actions.append(key.strip() or f'line {number}')
    if malformed_headers or malformed_actions:
        raise ValueError(
            f'generated INI parse failed; malformed headers={malformed_headers[:4]}, '
            f'Actions={malformed_actions[:4]}'
        )


def _validate_line_lengths(lines):
    section = ''
    maximum = 0
    for number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if stripped.startswith('[') and stripped.endswith(']'):
            section = stripped[1:-1].strip().lower()
        if section in PACKED_SECTIONS:
            continue
        length = len(line.encode('utf-8'))
        maximum = max(maximum, length)
        if length > MAX_MAP_ACTION_LINE_LENGTH:
            raise ValueError(
                f'generated line {number} in [{section}] is {length} bytes'
            )
    return maximum


def _validate_payloads(original, generated, markers, expected_count):
    registry_ids = {}
    all_ids = []
    for section, prefix in (
        ('TeamTypes', 'RLRVT'),
        ('TaskForces', 'RLRVF'),
        ('ScriptTypes', 'RLRVS'),
    ):
        values = _new_registry_ids(original, generated, section, prefix)
        registry_ids[section] = values
        all_ids.extend(values)

    if any(len(values) != expected_count for values in registry_ids.values()):
        raise ValueError('generated hook registry counts do not match markers')
    lowered = [item.lower() for item in all_ids]
    if len(lowered) != len(set(lowered)):
        raise ValueError('generated hook IDs are not unique')
    if any(
        not item.upper().startswith(GENERATED_HOOK_PREFIX)
        or len(item) > MAX_GENERATED_ID_LENGTH
        for item in all_ids
    ):
        raise ValueError('generated hook ID escaped namespace or length limit')

    action_team_ids = []
    generated_team_ids = {item.lower() for item in registry_ids['TeamTypes']}
    for line in section_lines(generated, 'Actions'):
        if '=' not in line:
            continue
        _key, value = line.split('=', 1)
        declared, groups = parse_action_groups(value)
        if declared != len(groups):
            continue
        action_team_ids.extend(
            group[2].lower() for group in groups
            if group[0] == '4' and group[2].lower() in generated_team_ids
        )
    if Counter(action_team_ids) != Counter(generated_team_ids):
        raise ValueError('generated marker teams are not registered exactly once')

    markers_by_name = {name.lower(): name for name in markers}
    for team_id in registry_ids['TeamTypes']:
        values = section_value_map_preserve(generated, team_id)
        marker = values.get('Name')
        taskforce_id = values.get('TaskForce')
        script_id = values.get('Script')
        if not marker or marker.lower() not in markers_by_name:
            raise ValueError(f'[{team_id}] has no registered marker payload')
        if not taskforce_id or taskforce_id not in registry_ids['TaskForces']:
            raise ValueError(f'[{team_id}] has unregistered TaskForce')
        if not script_id or script_id not in registry_ids['ScriptTypes']:
            raise ValueError(f'[{team_id}] has unregistered ScriptType')
        taskforce = section_value_map_preserve(generated, taskforce_id)
        script = section_value_map_preserve(generated, script_id)
        if taskforce.get('Name') != f'{marker} Empty' or taskforce.get('Group') != '-1':
            raise ValueError(f'[{taskforce_id}] marker payload is invalid')
        if script.get('0') != '11,5' or script.get('Name') != f'{marker} Guard':
            raise ValueError(f'[{script_id}] marker payload is invalid')
    return tuple(all_ids)


def release_validation_report():
    """Return the complete static release-gate report without writing maps."""
    installed_sections, rules_source = read_rules_sections()
    failures = []
    generated_hashes = {}
    deterministic = 0
    parseable = 0
    identity_preserved = 0
    mutation_scoped = 0
    payloads_registered = 0
    source_hashes_preserved = 0
    max_line_bytes = 0
    generated_id_count = 0

    for metadata in MISSION_METADATA:
        code = metadata['code']
        source_path = resolve_installed_scenario(metadata['scenario'])
        initial_hash = file_sha256(source_path)
        try:
            first = generate_victory_hook_map(metadata, installed_sections)
            second = generate_victory_hook_map(
                metadata, installed_sections, capture_identity=False
            )
            original, generated, contract, markers, action_ids, hook_count = first
            first_bytes = render_generated_hook_map(generated)
            second_bytes = render_generated_hook_map(second[1])
            if first_bytes != second_bytes:
                raise ValueError('equal inputs produced different map bytes')
            deterministic += 1
            generated_hashes[code] = hashlib.sha256(first_bytes).hexdigest()

            reparsed = IniLines(first_bytes.decode('utf-8').splitlines()[1:])
            generated_ids = _validate_payloads(
                original, reparsed, markers, hook_count
            )
            payloads_registered += 1
            generated_id_count += len(generated_ids)
            _validate_parse(
                reparsed,
                {str(item).lower() for item in action_ids},
                {str(item).lower() for item in generated_ids},
            )
            parseable += 1
            validate_authored_identity_contract(contract, reparsed)
            identity_preserved += 1
            _strip_approved_mutations(
                original, reparsed, action_ids, generated_ids
            )
            mutation_scoped += 1
            max_line_bytes = max(max_line_bytes, _validate_line_lengths(reparsed))

            if file_sha256(source_path) != initial_hash:
                raise ValueError('source map hash changed after validation')
            source_hashes_preserved += 1
        except Exception as exc:
            failures.append({'code': code, 'error': str(exc)})

    mission_count = len(MISSION_METADATA)
    static_valid = not failures and all(value == mission_count for value in (
        deterministic,
        parseable,
        identity_preserved,
        mutation_scoped,
        payloads_registered,
        source_hashes_preserved,
    ))
    pending_gameplay_checks = [] if GAMEPLAY_CATALOGUES_READY else [
        'generated player-production clone registration',
        'locked technology absent from player production',
        'approved buff and shared-weapon isolation',
    ]
    pending_live_checks = [
        'one launch per campaign family and active faction',
        'no-build and trigger-critical mission launches',
        'all 108 launch-smoke checks',
        'complete campaign playthroughs',
    ]
    return {
        'rules_source': rules_source,
        'mission_count': mission_count,
        'deterministic_missions': deterministic,
        'parseable_generated_missions': parseable,
        'source_hash_preserved_missions': source_hashes_preserved,
        'identity_preserved_missions': identity_preserved,
        'taskforce_identity_preserved_missions': identity_preserved,
        'approved_hook_scope_missions': mutation_scoped,
        'hook_payload_registration_missions': payloads_registered,
        'generated_hook_id_count': generated_id_count,
        'generated_output_hashes': dict(sorted(generated_hashes.items())),
        'max_nonpacked_line_bytes': max_line_bytes,
        'line_limit_bytes': MAX_MAP_ACTION_LINE_LENGTH,
        'gameplay_generation_checks_available': GAMEPLAY_CATALOGUES_READY,
        'pending_gameplay_checks': pending_gameplay_checks,
        'pending_live_checks': pending_live_checks,
        'failures': failures,
        'static_valid': static_valid,
        'release_ready': (
            static_valid
            and GAMEPLAY_CATALOGUES_READY
            and not pending_gameplay_checks
            and not pending_live_checks
        ),
        'valid': static_valid,
    }


def main():
    report = release_validation_report()
    print(json.dumps(report, indent=2))
    return 0 if report['valid'] else 1


if __name__ == '__main__':
    raise SystemExit(main())
