"""Imports, engine limits, and immutable map-generation policy."""

import hashlib

import re

import shutil

from datetime import datetime

from randomizer.core.collections import comma_items, unique_in_order

from randomizer.maps.ini import (
    action_group_tokens,
    all_section_value_maps,
    append_section_entry,
    find_section_bounds,
    merge_ini_section_values,
    next_numeric_section_index,
    parse_action_groups,
    read_text,
    section_lines,
    section_value_map,
    section_value_map_preserve,
)

from randomizer.maps.ownership import (
    ai_trigger_team_usage_houses,
    build_unit_usage_index,
    directly_created_team_ids,
    script_referenced_team_ids,
    script_referenced_taskforce_unit_ids,
    scripted_enemy_house_pairs,
    taskforce_usage_houses,
    techno_type_possible_houses,
    unit_usage_houses,
    unsafe_country_houses,
)

from randomizer.maps.houses import (
    canonical_house_name,
    country_family,
    map_house_records,
    player_controlled_houses,
    player_house_from_map,
    production_owner_countries,
    resolve_configured_helper_houses,
)

from randomizer.maps.hooks import unique_section_key

from randomizer.core.paths import BACKUP_DIR

from randomizer.rewards.rules import (
    buffs_with_unlocked_access,
    expand_equivalent_role_buffs,
)

from randomizer.rewards.catalogue import (
    ALWAYS_AVAILABLE_UNIT_IDS,
    ALWAYS_AVAILABLE_TECH_IDS,
    BUFF_TARGETS,
    CLONE_REQUIRED_BUFF_TYPES,
    ENGINEER_UNIT_IDS,
    HOUSE_SCOPED_BUFF_TYPES,
    FACTION_UNIT_ROSTERS,
    LIMITED_HERO_UNIT_IDS,
    MANDATORY_EXCLUDED_BUFF_TYPE_IDS,
    NONTRAINABLE_UNIT_IDS,
    REWARD_POOL,
    STANDALONE_WEAPON_TEMPLATES,
    STANDALONE_UNIT_RULE_TEMPLATES,
    WEAPON_STAT_BUFF_TYPES,
    capped_movement_speed,
    buff_stack_limit,
    canonical_reward,
    canonical_rewards,
    house_category_suffix,
    house_wide_buff_scope,
    linked_buff_variant_ids,
    movement_speed_ceiling,
    unit_role_equivalents,
)

from randomizer.rewards.reloaded_weapon_stats import WEAPON_USER_IDS

from randomizer.config.static import load_static_config

from randomizer.config.tuning import (
    BUFF_EFFECTS,
    CLONE_POLICY,
    CLONE_UI_DESCRIPTION,
    MISSION_ASSISTANCE,
    stacking_amount,
    stacking_multiplier,
)

_MAP_CONFIG = load_static_config('map_rules.json')

_ENGINE_LIMITS = _MAP_CONFIG['engine_limits']

_ENGINEER_CLONE_SAFETY = _MAP_CONFIG.get('engineer_clone_safety', {
    'identity_fields': {
        'Primary': 'DefuseKit',
        'Secondary': 'EngineerScanner',
        'Engineer': 'yes',
        'CanDrive': 'yes',
        'GroupAs': 'Engineers',
        'IFVMode': '1',
        'PhysicalSize': '1',
        'Size': '1',
        'Locomotor': '{4A582744-9839-11d1-B709-00A024DDAFD1}',
        'MovementZone': 'Infantry',
        'SpeedType': 'Foot',
    },
    'removed_fields': [
        'Teleporter', 'ChronoInSound', 'ChronoOutSound', 'ChronoTrigger',
        'Chronoshift.Allow', 'Chronoshift.IsVehicle',
    ],
})

RANDOMIZED_SUPERWEAPON_BUILDINGS = {
    category: frozenset(str(item).upper() for item in building_ids)
    for category, building_ids in _MAP_CONFIG.get(
        'randomized_superweapon_buildings', {}
    ).items()
}

HOOKED_MAP_MARKER = '; Generated by C&C Reloaded Randomizer Launcher objective hook'

RANDOMIZER_TYPE_LIST_KEY_START = int(_ENGINE_LIMITS['randomizer_type_list_key_start'])

RANDOMIZER_SUPERWEAPON_PREFIX = str(_ENGINE_LIMITS['randomizer_superweapon_prefix'])

RANDOMIZER_SUPERWEAPON_CAMEO_PRIORITY = '10000'

MAX_ARES_TYPE_ID_LENGTH = int(_ENGINE_LIMITS['max_ares_type_id_length'])

EXTRA_TECH_LOCKS = set(_MAP_CONFIG['extra_tech_locks'])

SCRIPTED_TECH_LOCK_EXCLUSIONS = set(_MAP_CONFIG['scripted_tech_lock_exclusions'])

SCRIPTED_TECH_BUILD_LIMIT = str(_ENGINE_LIMITS['scripted_tech_build_limit'])

RANDOMIZER_RULES_MARKER = '; Generated by C&C Reloaded Randomizer Launcher'

LOCKED_TECH_LEVEL = str(_ENGINE_LIMITS['locked_tech_level'])

UNLOCKED_TECH_LEVEL = str(_ENGINE_LIMITS['unlocked_tech_level'])

MISSION_ASSISTANCE_CATEGORIES = tuple(_ENGINE_LIMITS['mission_assistance_categories'])

MAX_MAP_ACTION_LINE_LENGTH = int(_ENGINE_LIMITS['max_map_action_line_length'])

MAX_COUNTRY_VETERAN_VALUE_LENGTH = int(_ENGINE_LIMITS['max_country_veteran_value_length'])

SUPERWEAPON_ACTIONS_PER_TRIGGER = int(
    _ENGINE_LIMITS['superweapon_actions_per_trigger']
)

_COMPACT_CLONE_ID_FIRST = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

_COMPACT_CLONE_ID_SECOND = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

_FIXED_PLAYER_CLONE_IDS = frozenset({'CHITZ', 'VOLKOV'})

SHARED_WEAPON_USER_IDS = {
    weapon_id: set(unit_ids)
    for weapon_id, unit_ids in WEAPON_USER_IDS.items()
}

TECHNO_TYPE_LISTS = dict(_MAP_CONFIG['techno_type_lists'])
